export const IMAGE_REVEAL_DURATION_SECONDS = 1.6;
export const GALLERY_ITEM_REVEAL_DURATION_SECONDS = 1.2;
export const GALLERY_AUTOPLAY_INTERVAL_MS = 6500;
export const GALLERY_FILMSTRIP_AUTOPLAY_INTERVAL_MS = 6500;
export const GALLERY_SCROLL_RESUME_DELAY_MS = 8000;
